// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import Ts__FilterController from "./ts/filter_controller.js"
application.register("ts--filter", Ts__FilterController)

import Ts__SearchController from "./ts/search_controller.js"
application.register("ts--search", Ts__SearchController)

import Ts__SelectController from "./ts/select_controller.js"
application.register("ts--select", Ts__SelectController)
