// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import TomSelectController from "./tom_select_controller.js"
application.register("tom-select", TomSelectController)

import Ts__FilterController from "./ts/filter_controller.js"
application.register("ts--filter", Ts__FilterController)
