default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  encoding: unicode
  host: localhost
  port: 5432

development:
  <<: *default
  username: postgres
  database: ts
  password: teste1

production:
  <<: *default
  username: rails
  database: ts
  password: <%= ENV['DB_PASSWORD'] %>
